// <auto-generated />
using System;
using DbUser;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbUser.Migrations
{
    [DbContext(typeof(UserDataContext))]
    partial class UserDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbUser.Ms_voucher", b =>
                {
                    b.Property<decimal?>("id_voucher")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("id_user")
                        .HasColumnType("numeric");

                    b.Property<string>("kodegenerate")
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.Property<DateOnly?>("tgl_generate")
                        .HasColumnType("date");

                    b.HasKey("id_voucher")
                        .HasName("PK_vouchers");

                    b.HasIndex("id_user");

                    b.ToTable("ms_Vouchers");
                });

            modelBuilder.Entity("DbUser.User", b =>
                {
                    b.Property<decimal?>("Id_user")
                        .HasColumnType("numeric");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nama_user")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("no_hp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("noktp")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("tgl_input")
                        .HasColumnType("date");

                    b.HasKey("Id_user")
                        .HasName("PK_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DbUser.UserLogin", b =>
                {
                    b.Property<decimal?>("id_userlogin")
                        .HasColumnType("numeric");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("user_id")
                        .HasColumnType("numeric");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_userlogin")
                        .HasName("PK_userlogin");

                    b.HasIndex("user_id");

                    b.ToTable("Userlogins");
                });

            modelBuilder.Entity("DbUser.Ms_voucher", b =>
                {
                    b.HasOne("DbUser.User", "User")
                        .WithMany("Fk_voucherss")
                        .HasForeignKey("id_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbUser.UserLogin", b =>
                {
                    b.HasOne("DbUser.User", "User")
                        .WithMany("Fk_userlogins")
                        .HasForeignKey("user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbUser.User", b =>
                {
                    b.Navigation("Fk_userlogins");

                    b.Navigation("Fk_voucherss");
                });
#pragma warning restore 612, 618
        }
    }
}
